#test
management:
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
        redis:
            enabled: false
        rabbitmq:
            enabled: false
    security:
      enabled: false


